services:
  web:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: postgres
    environment:
      POSTGRES_DB: 'lyricboxd'
      POSTGRES_USER: 'lyricboxd'
      POSTGRES_PASSWORD: '123321'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
